### ISSUE TITLE
The download is not working 

### ISSUE THREAD

**Issue by Dziney** [ulif/fpscan#1]
Hi! I want to flash my phone to print it, but I can't download the file, why?
![Screenshot_2024-01-29-23-40-35-61_21da60175e70af211acc4f26191b7a77](https://github.com/ulif/fpscan/assets/132850029/ee763770-4621-4e87-aec9-4f0153e4f686)

**Comment by ulif** [comment]
Thanks for your strange request,

why would one look for downloads in the **up**load section?

Also in the repo you will find source code you have to compile (on a Linux system) to create an executable. I don't understand what flashing your phone "to print" it could mean.
